import { useEffect, useMemo, useRef, useState } from 'react';
import type { 角色数据结构 } from '@/models/character';
import type { 聊天消息 } from '@/models/chat';
import type { 相册系统 } from '@/models/imageGeneration';
import { 归一化NPC记录列表, type NPC记录 } from '@/models/npc';
import type { 新闻条目 } from '@/models/news';
import type {
  手机会话,
  手机联系人,
  手机消息,
  手机系统,
  主动来信种子,
} from '@/models/phone';
import {
  创建手机消息,
  创建手机会话,
  创建手机会话本地库,
  创建手机会话本地摘要条目,
  计算手机未读,
} from '@/models/phone';
import type { API设置, 游戏设置 } from '@/models/settings';
import type { 世界状态 } from '@/models/world';
import type { 智库系统 } from '@/models/zhiku';
import { DEFAULT_PHONE_CHAT_WALLPAPER, DEFAULT_PHONE_HOME_WALLPAPER } from '@/data/builtinPhoneWallpapers';
import type { PhoneMemoryCommitInput, 手机回复上下文 } from '@/contracts/phone';
import { 解析相册资源引用 } from '@/utils/albumActions';
import {
  buildFallbackContactsFromStory,
  buildStandardGroupTitle,
  computeLocalArchiveFlush,
  createReplyMessages,
  deriveAddableContacts,
  deriveContacts,
  findExistingGroupChat,
  getSeedCooldown,
  isSeedCoolingDown,
  mergeContacts,
  normalizeParticipantId,
  resolveContactByParticipantId,
  resolveContactForChat,
  resolveSeedContact,
  selectAutoSeed,
} from '@/utils/phone';

export type PhoneApp = 'messages' | 'contacts' | 'news' | 'wallpapers';
export type MobilePhoneView = 'list' | 'chat' | 'contact';
export type MessageListMode = 'private' | 'group';

export interface PhoneModalProps {
  phone: 手机系统;
  traveler: 角色数据结构;
  world: 世界状态;
  news: 新闻条目[];
  zhiku: 智库系统;
  apiSettings: API设置;
  gameSettings: 游戏设置;
  turnCount: number;
  mainChatHistory: 聊天消息[];
  npcRecords: NPC记录[];
  album?: 相册系统;
  onPhoneChange: React.Dispatch<React.SetStateAction<手机系统>>;
  /** 记忆用例动作：即时追加 + 归档压缩 + NPC 台账压缩（由 App 从 useGame 门面注入）。 */
  onPhoneMemoryCommit: (input: PhoneMemoryCommitInput) => Promise<void>;
  /** 手机 AI 回复用例动作：封装配置构建与生成，失败时返回空字符串（由 App 从 useGame 门面注入）。 */
  onGeneratePhoneReply: (apiConfig: API设置, context: 手机回复上下文) => Promise<string>;
  onClose: () => void;
}

export function usePhone(props: PhoneModalProps) {
  const {
    phone,
    traveler,
    world,
    news,
    zhiku,
    apiSettings,
    gameSettings,
    turnCount,
    mainChatHistory,
    npcRecords,
    album,
    onPhoneChange,
    onPhoneMemoryCommit,
    onGeneratePhoneReply,
  } = props;

  const [activeApp, setActiveApp] = useState<PhoneApp | null>(null);
  const [activeChatId, setActiveChatId] = useState(phone.chats[0]?.id ?? '');
  const [activeContactId, setActiveContactId] = useState(phone.contacts[0]?.id ?? '');
  const [draft, setDraft] = useState('');
  const [sendingChatId, setSendingChatId] = useState('');
  const [generatingSeedId, setGeneratingSeedId] = useState('');
  const autoGeneratedSeedRef = useRef('');
  const [phoneError, setPhoneError] = useState('');
  const [showCreateGroup, setShowCreateGroup] = useState(false);
  const [showPendingSeeds, setShowPendingSeeds] = useState(false);
  const [messageListMode, setMessageListMode] = useState<MessageListMode>('private');
  const [showAddContact, setShowAddContact] = useState(false);
  const [groupNameDraft, setGroupNameDraft] = useState('');
  const [groupMemberIds, setGroupMemberIds] = useState<string[]>([]);
  const [mobileView, setMobileView] = useState<MobilePhoneView>('list');

  const normalizedNpcRecords = useMemo(() => 归一化NPC记录列表(npcRecords), [npcRecords]);
  const derivedContacts = useMemo(() => deriveContacts(normalizedNpcRecords, album), [album, normalizedNpcRecords]);
  const fallbackStoryContacts = useMemo(
    () => buildFallbackContactsFromStory({ mainChatHistory, world, existingContacts: phone.contacts, turnCount }),
    [mainChatHistory, phone.contacts, turnCount, world],
  );
  const contacts = useMemo(
    () => mergeContacts(phone.contacts, derivedContacts, fallbackStoryContacts, normalizedNpcRecords, album),
    [album, derivedContacts, fallbackStoryContacts, normalizedNpcRecords, phone.contacts],
  );
  const addableNpcContacts = useMemo(
    () => deriveAddableContacts(normalizedNpcRecords, phone.contacts, album),
    [album, normalizedNpcRecords, phone.contacts],
  );

  const activeChat = phone.chats.find((chat) => chat.id === activeChatId) ?? phone.chats.at(0);
  const activeContact = contacts.find((contact) => contact.id === activeContactId) ?? contacts.at(0);

  const pendingSeeds = phone.messageSeeds.filter((seed) => seed.status === 'pending');
  const privateChats = useMemo(() => phone.chats.filter((chat) => chat.type !== 'group'), [phone.chats]);
  const groupChats = useMemo(() => phone.chats.filter((chat) => chat.type === 'group'), [phone.chats]);
  const visibleChats = messageListMode === 'group' ? groupChats : privateChats;
  const phoneEnabled = gameSettings.手机系统.enabled;

  const autoSeed = useMemo(
    () => selectAutoSeed(pendingSeeds, phone, turnCount, gameSettings, generatingSeedId, phoneEnabled),
    [gameSettings, generatingSeedId, pendingSeeds, phone, phoneEnabled, turnCount],
  );

  const unreadTotal = 计算手机未读(phone);
  const homeWallpaper = 解析相册资源引用(album, phone.wallpapers?.home) || DEFAULT_PHONE_HOME_WALLPAPER;
  const chatWallpaperSetting = 解析相册资源引用(album, phone.wallpapers?.chat) || DEFAULT_PHONE_CHAT_WALLPAPER;
  const chatWallpaper =
    activeApp === 'messages' ? chatWallpaperSetting : undefined;

  const groupMembers =
    activeChat?.type === 'group'
      ? activeChat.participantIds
          .map((id) => resolveContactByParticipantId(contacts, normalizedNpcRecords, id))
          .filter((item): item is 手机联系人 => Boolean(item))
      : [];
  const groupAddCandidates =
    activeChat?.type === 'group'
      ? contacts.filter((contact) => {
          if (!contact.available) return false;
          return !activeChat.participantIds.some((participantId) => {
            const normalized = normalizeParticipantId(contacts, participantId);
            return (
              participantId === contact.id ||
              participantId === contact.npcId ||
              normalized === contact.id ||
              (contact.npcId ? normalized === normalizeParticipantId(contacts, contact.npcId) : false)
            );
          });
        })
      : [];

  const wait = (ms: number) => new Promise((resolve) => window.setTimeout(resolve, ms));

  // unreadTotal 是持久化反规范化字段，App 外壳（LeftPanel/MobileQuickMenu）直接消费
  // state.手机.unreadTotal，必须每次写路径回填，不能只在本地派生。
  const updatePhone = (updater: (prev: 手机系统) => 手机系统) => {
    onPhoneChange((prev) => {
      const next = updater(prev);
      return { ...next, unreadTotal: 计算手机未读(next) };
    });
  };

  const dismissSeed = (seed: 主动来信种子) => {
    updatePhone((prev) => ({
      ...prev,
      messageSeeds: prev.messageSeeds.map((item) => (item.id === seed.id ? { ...item, status: 'dismissed' as const } : item)),
    }));
  };

  const markChatRead = (chatId: string) => {
    updatePhone((prev) => ({
      ...prev,
      chats: prev.chats.map((chat) => (chat.id === chatId ? { ...chat, unread: 0 } : chat)),
    }));
  };

  const updateChatMessages = (chatId: string, updater: (chat: 手机会话) => 手机会话) => {
    updatePhone((prev) => ({
      ...prev,
      chats: prev.chats.map((chat) => (chat.id === chatId ? updater(chat) : chat)),
    }));
  };

  const appendMessagesToChat = (chatId: string, messages: 手机消息[], unread = 0) => {
    updatePhone((prev) => ({
      ...prev,
      chats: prev.chats.map((chat) =>
        chat.id === chatId
          ? { ...chat, messages: [...chat.messages, ...messages], unread: Math.max(0, unread), updatedAt: Date.now() }
          : chat,
      ),
    }));
  };

  const appendMessagesToChatSequentially = async (chatId: string, messages: 手机消息[], unread = 0) => {
    for (let index = 0; index < messages.length; index += 1) {
      if (index > 0) await wait(620);
      appendMessagesToChat(chatId, [messages[index]], index === messages.length - 1 ? unread : 0);
    }
  };

  const ensurePrivateChat = (contact: 手机联系人): 手机会话 => {
    const existing = phone.chats.find((chat) => chat.type === 'private' && chat.participantIds.includes(contact.id));
    if (existing) {
      setActiveChatId(existing.id);
      setActiveApp('messages');
      setMobileView('chat');
      markChatRead(existing.id);
      return existing;
    }
    const newChat = 创建手机会话({ type: 'private', title: contact.name, participantIds: [contact.id] });
    newChat.localArchive = {
      ...(newChat.localArchive ?? 创建手机会话本地库('private')),
      threshold: gameSettings.手机系统.privateArchiveThreshold,
    };
    updatePhone((prev) => {
      const hasContact = prev.contacts.some((item) => item.id === contact.id);
      const next = {
        ...prev,
        contacts: hasContact ? prev.contacts : [...prev.contacts, contact],
        chats: [newChat, ...prev.chats],
      };
      return next;
    });
    setActiveChatId(newChat.id);
    setActiveApp('messages');
    setMobileView('chat');
    return newChat;
  };

  const handleAddContact = (contact: 手机联系人) => {
    updatePhone((prev) => {
      if (prev.contacts.some((item) => item.id === contact.id || (contact.npcId && item.npcId === contact.npcId))) {
        return prev;
      }
      return {
        ...prev,
        contacts: [
          {
            ...contact,
            available: true,
            status: 'available',
            unlockSource: 'manual',
            lastActiveTurn: contact.lastActiveTurn ?? turnCount,
          },
          ...prev.contacts,
        ],
      };
    });
    setActiveContactId(contact.id);
    setShowAddContact(false);
    setPhoneError('');
  };

  const handleCreateGroupChat = () => {
    const selectedContacts = contacts.filter((contact) => groupMemberIds.includes(contact.id) && contact.available);
    if (selectedContacts.length < 2) {
      setPhoneError('创建群聊至少需要选择 2 位可联系对象。');
      return;
    }
    const title = groupNameDraft.trim() || buildStandardGroupTitle(selectedContacts);
    const groupChat = 创建手机会话({
      type: 'group',
      title,
      participantIds: selectedContacts.map((item) => item.id),
    });
    groupChat.localArchive = {
      ...(groupChat.localArchive ?? 创建手机会话本地库('group')),
      threshold: gameSettings.手机系统.groupArchiveThreshold,
    };
    updatePhone((prev) => ({ ...prev, chats: [groupChat, ...prev.chats] }));
    setActiveChatId(groupChat.id);
    setActiveApp('messages');
    setMobileView('list');
    setShowCreateGroup(false);
    setGroupNameDraft('');
    setGroupMemberIds([]);
    setPhoneError('');
  };

  const appendPhoneLocalSummary = (
    chat: 手机会话,
    summary: string,
    source: 'private' | 'group' | 'system',
    messageCount: number,
    seedId?: string,
  ): string => {
    const entry = 创建手机会话本地摘要条目({ turn: turnCount, summary, source, messageCount, sourceSeedId: seedId });
    const { nextArchive, flushedSummary } = computeLocalArchiveFlush(
      chat,
      entry,
      {
        group: gameSettings.手机系统.groupArchiveThreshold,
        private: gameSettings.手机系统.privateArchiveThreshold,
      },
      turnCount,
    );
    updateChatMessages(chat.id, (currentChat) => ({ ...currentChat, localArchive: nextArchive }));
    return flushedSummary;
  };

  const commitPhoneMemory = async (summary: string, contact?: 手机联系人, options: { force?: boolean } = {}) => {
    await onPhoneMemoryCommit({ summary, npcId: contact?.npcId, force: options.force });
  };

  const handleSelectChat = (chatId: string) => {
    setActiveChatId(chatId);
    markChatRead(chatId);
    setMobileView('chat');
  };

  const handleRenameGroupChat = (chatId: string, title: string) => {
    const nextTitle = title.trim().slice(0, 24);
    if (!nextTitle) {
      setPhoneError('群聊名称不能为空。');
      return;
    }
    updateChatMessages(chatId, (chat) =>
      chat.type === 'group' ? { ...chat, title: nextTitle, updatedAt: Date.now() } : chat,
    );
    setPhoneError('');
  };

  const handleAddGroupMember = (chatId: string, contact: 手机联系人) => {
    updateChatMessages(chatId, (chat) => {
      if (chat.type !== 'group') return chat;
      const alreadyInGroup = chat.participantIds.some((participantId) => {
        const normalized = normalizeParticipantId(contacts, participantId);
        return (
          participantId === contact.id ||
          participantId === contact.npcId ||
          normalized === contact.id ||
          (contact.npcId ? normalized === normalizeParticipantId(contacts, contact.npcId) : false)
        );
      });
      if (alreadyInGroup) return chat;
      return { ...chat, participantIds: [...chat.participantIds, contact.id], updatedAt: Date.now() };
    });
    setPhoneError('');
  };

  const handleStartChat = (contact: 手机联系人) => {
    setActiveContactId(contact.id);
    ensurePrivateChat(contact);
    setMobileView('chat');
  };

  const handleSendPhoneMessage = async () => {
    const text = draft.trim();
    if (!text || !activeChat || sendingChatId) return;
    if (!phoneEnabled) {
      setPhoneError('手机系统已在设置中关闭。');
      return;
    }
    if (!gameSettings.手机系统.autoGenerateSeeds) {
      setPhoneError('主动来信已在设置中关闭。');
      return;
    }
    setPhoneError('');
    setDraft('');
    setSendingChatId(activeChat.id);

    const playerMessage = 创建手机消息({
      senderId: 'player',
      senderName: traveler.姓名 || '我',
      role: 'player',
      avatar: traveler.图像档案?.手机头像 || traveler.头像 || undefined,
      content: text,
      turn: turnCount,
    });
    const chatAfterPlayer: 手机会话 = {
      ...activeChat,
      messages: [...activeChat.messages, playerMessage],
      unread: 0,
      updatedAt: Date.now(),
    };
    updateChatMessages(activeChat.id, () => chatAfterPlayer);

    try {
      const contact = resolveContactForChat(contacts, activeChat);
      const replyText = await onGeneratePhoneReply(apiSettings, {
        traveler,
        world,
        npcRecords,
        news,
        turnCount,
        chat: chatAfterPlayer,
        contacts,
        contact,
        userText: text,
        mainChatHistory,
        zhiku,
      });
      if (!replyText) {
        setPhoneError('回复生成失败：请检查 API 配置后重试。');
        return;
      }
      const replyMessages = replyText.split('\n').filter(Boolean);
      await appendMessagesToChatSequentially(
        activeChat.id,
        createReplyMessages(activeChat, replyMessages, contacts, normalizedNpcRecords, turnCount, contact),
        0,
      );
      const flushedSummary = appendPhoneLocalSummary(
        chatAfterPlayer,
        replyText,
        activeChat.type === 'group' ? 'group' : 'private',
        replyMessages.length,
      );
      await commitPhoneMemory(
        `手机${activeChat.type === 'group' ? `群聊「${activeChat.title}」` : contact ? `私聊「${contact.name}」` : '私聊'}：${replyText}`,
        contact,
        { force: true },
      );
      if (flushedSummary) {
        await commitPhoneMemory(flushedSummary, contact);
      }
    } catch (err) {
      setPhoneError(`发送失败：${(err as Error).message}`);
    } finally {
      setSendingChatId('');
    }
  };

  const handleGenerateSeed = async (seed: 主动来信种子) => {
    if (generatingSeedId) return;
    if (!phoneEnabled) {
      setPhoneError('手机系统已在设置中关闭。');
      return;
    }
    if (isSeedCoolingDown(seed, phone, turnCount, gameSettings)) {
      const cooldown = getSeedCooldown(seed, gameSettings);
      setPhoneError(`该来信仍在冷却中（${cooldown} 回合）。可以稍后再打开，紧急来信会自动绕过冷却。`);
      return;
    }
    setPhoneError('');
    setGeneratingSeedId(seed.id);

    const contact = resolveSeedContact(contacts, normalizedNpcRecords, seed);
    if (seed.targetType === 'private' && !contact.available) {
      setPhoneError('该对象尚未作为联系人解锁。');
      setGeneratingSeedId('');
      return;
    }
    const groupParticipantIds = (seed.relatedNpcIds.length ? seed.relatedNpcIds : [seed.targetId])
      .map((id) => normalizeParticipantId(contacts, id))
      .filter(Boolean);
    const groupTitleContacts = groupParticipantIds
      .map((id) => resolveContactByParticipantId(contacts, normalizedNpcRecords, id))
      .filter((item): item is 手机联系人 => Boolean(item));
    const groupTitle = buildStandardGroupTitle(groupTitleContacts, seed.title);
    const groupByTargetId =
      seed.targetType === 'group'
        ? phone.chats.find((item) => item.type === 'group' && item.id === seed.targetId)
        : undefined;
    const existingGroup =
      seed.targetType === 'group'
        ? groupByTargetId ?? findExistingGroupChat(phone.chats, contacts, groupParticipantIds, groupTitle)
        : undefined;
    const chat =
      seed.targetType === 'group'
        ? existingGroup ??
          创建手机会话({
            type: 'group',
            title: groupTitle,
            participantIds:
              groupParticipantIds.length >= 2
                ? groupParticipantIds
                : [normalizeParticipantId(contacts, seed.targetId), ...groupParticipantIds].filter(Boolean),
          })
        : ensurePrivateChat(contact);

    if (seed.targetType === 'group') {
      chat.localArchive = {
        ...(chat.localArchive ?? 创建手机会话本地库('group')),
        threshold: gameSettings.手机系统.groupArchiveThreshold,
      };
    }

    if (seed.targetType === 'group') {
      updatePhone((prev) => {
        const exists = prev.chats.find((item) => item.id === chat.id);
        return { ...prev, chats: exists ? prev.chats : [chat, ...prev.chats] };
      });
      setActiveChatId(chat.id);
      setActiveApp('messages');
      setMobileView('chat');
    }

    try {
      const replyText = await onGeneratePhoneReply(apiSettings, {
        traveler,
        world,
        npcRecords,
        news,
        turnCount,
        chat,
        contacts,
        contact: seed.targetType === 'private' ? contact : undefined,
        seed,
        mainChatHistory,
        zhiku,
      });
      if (!replyText) {
        setPhoneError('来信生成失败：请检查 API 配置后重试。');
        return;
      }
      const replyMessages = replyText.split('\n').filter(Boolean);
      updatePhone((prev) => {
        const hasContact = prev.contacts.some((item) => item.id === contact.id);
        return {
          ...prev,
          contacts: seed.targetType === 'private' && !hasContact ? [...prev.contacts, contact] : prev.contacts,
          messageSeeds: prev.messageSeeds.map((item) =>
            item.id === seed.id ? { ...item, status: 'generated' as const } : item,
          ),
        };
      });
      await appendMessagesToChatSequentially(
        chat.id,
        createReplyMessages(
          chat,
          replyMessages,
          contacts,
          normalizedNpcRecords,
          turnCount,
          seed.targetType === 'private' ? contact : undefined,
          seed.id,
        ),
        0,
      );
      const flushedSummary = appendPhoneLocalSummary(
        chat,
        replyText,
        seed.targetType === 'group' ? 'group' : 'private',
        replyMessages.length,
        seed.id,
      );
      await commitPhoneMemory(
        `主动来信「${seed.title}」：${replyText}`,
        seed.targetType === 'private' ? contact : undefined,
        { force: true },
      );
      if (flushedSummary) {
        await commitPhoneMemory(flushedSummary, seed.targetType === 'private' ? contact : undefined);
      }
      setActiveChatId(chat.id);
      setActiveApp('messages');
      setMobileView('chat');
    } catch (err) {
      setPhoneError(`生成来信失败：${(err as Error).message}`);
    } finally {
      setGeneratingSeedId('');
    }
  };

  const handleGenerateSeedRef = useRef(handleGenerateSeed);
  useEffect(() => {
    handleGenerateSeedRef.current = handleGenerateSeed;
  });

  useEffect(() => {
    if (!autoSeed || autoGeneratedSeedRef.current) return;
    autoGeneratedSeedRef.current = autoSeed.id;
    void handleGenerateSeedRef.current(autoSeed);
  }, [autoSeed]);

  const openApp = (app: PhoneApp) => {
    setActiveApp(app);
    setMobileView('list');
  };
  const closeApp = () => {
    setActiveApp(null);
    setMobileView('list');
  };
  const backToList = () => setMobileView('list');
  const toggleGroupMember = (id: string) => {
    setGroupMemberIds((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
  };
  const setWallpaper = (kind: 'home' | 'chat', src: string | undefined) => {
    updatePhone((prev) => ({ ...prev, wallpapers: { ...(prev.wallpapers ?? {}), [kind]: src } }));
  };

  const isSeedCoolingDownFor = (seed: 主动来信种子) => isSeedCoolingDown(seed, phone, turnCount, gameSettings);

  const state = {
    activeApp,
    activeChatId,
    activeContactId,
    mobileView,
    messageListMode,
    draft,
    sendingChatId,
    generatingSeedId,
    phoneError,
    showCreateGroup,
    showPendingSeeds,
    showAddContact,
    groupNameDraft,
    groupMemberIds,
    contacts,
    addableNpcContacts,
    chatCount: phone.chats.length,
    privateChats,
    groupChats,
    visibleChats,
    pendingSeeds,
    activeChat,
    activeContact,
    groupMembers,
    groupAddCandidates,
    unreadTotal,
    homeWallpaper,
    chatWallpaper,
    chatWallpaperSetting,
    isSeedCoolingDown: isSeedCoolingDownFor,
  };

  const actions = {
    openApp,
    closeApp,
    backToList,
    selectChat: handleSelectChat,
    startChat: handleStartChat,
    selectContact: (contactId: string) => {
      setActiveContactId(contactId);
      setMobileView('contact');
    },
    setDraft,
    setMessageListMode,
    toggleCreateGroup: () => setShowCreateGroup((v) => !v),
    togglePendingSeeds: () => setShowPendingSeeds((v) => !v),
    toggleAddContact: () => setShowAddContact((v) => !v),
    setGroupNameDraft,
    toggleGroupMember,
    sendMessage: handleSendPhoneMessage,
    generateSeed: handleGenerateSeed,
    dismissSeed,
    addContact: handleAddContact,
    createGroup: handleCreateGroupChat,
    renameGroup: handleRenameGroupChat,
    addGroupMember: handleAddGroupMember,
    setWallpaper,
  };

  return { state, actions };
}

export type PhoneState = ReturnType<typeof usePhone>['state'];
export type PhoneActions = ReturnType<typeof usePhone>['actions'];
